### ISSUE TITLE
Support Home Assiatant 2021.4.0

### ISSUE THREAD

**Issue by Kisty** [DaviPtrs/hass-unified-remote#11]
Hi there! Thanks for this great integration.

Have just ran Check Configuration addon against the latest version of HA and it seems that fhe integration isn't compatible at present.

Unsure what the version is but I cloned 17th Jan 2021.

### Check Config logs
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
bind failed: Address in use
error binding udev control socket
[04:01:22] INFO: Update udev information
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[04:01:22] INFO: Setup udev devices
[04:01:23] INFO: Don't worry, this temporary installation is not overwriting your current one.
[04:01:23] INFO: Installing Home Assistant: latest...
[04:01:23] INFO: Please be patient, this might take a few minutes...
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.
We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.
requests 2.25.1 requires idna<3,>=2.5, but you'll have idna 3.1 which is incompatible.
[04:10:38] INFO: Installed Home Assistant 2021.4.0
[04:10:38] INFO: Making a copy of your configuration for checking...
[04:12:00] INFO: Checking your configuration against this version...
[04:37:00] ERROR: The configuration check did not pass!
[04:37:00] ERROR: See the output below for more details.
Testing configuration at /tmp/config
INFO:custom_components.unified_remote:Remotes loaded sucessful
ERROR:homeassistant.helpers.check_config:Unexpected error validating config
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3012, in _dep_map
    return self.__dep_map
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2810, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3003, in _parsed_pkg_info
    return self._pkg_info
[04:37:00] INFO: The full output has been written to /share/check_config.txt
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
s6-ftrigrd: fatal: unable to sync with client: Broken pipe
s6-svwait: fatal: unable to ftrigr_startf: Operation timed out
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by Kisty** [comment]
Begging your pardon. I don't think this is related to this integration. I miss read the logs. Closing for now
