### ISSUE TITLE
Integration 'unified_remote' not found.

### ISSUE THREAD

**Issue by stevland** [DaviPtrs/hass-unified-remote#18]
Home Assistant 2023.5.3
Supervisor 2023.04.1
Operating System 10.1
Frontend 20230503.3

I'm a complete HA newbie BUT I believe I have configured everything correctly.

![2023-05-28 18 07 57](https://github.com/DaviPtrs/hass-unified-remote/assets/15148803/7058cf3d-2605-430d-ad3c-e12015c7f782)

In configuration.yaml

```
# Unified Remote
unified_remote:
  hosts:
    - host: 192.168.2.17
      port: 9510
  retry_delay: 60
```

But I receive the following:

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/homeassistant/__init__.py:316
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 17:15:17 (7 occurrences)
Last logged: 17:54:47

[140639050300864] Cannot quick reload all YAML configurations because the configuration is not valid: Integration error: unified_remote - Integration 'unified_remote' not found.
[140639049012544] Cannot quick reload all YAML configurations because the configuration is not valid: Integration error: unified_remote - Integration 'unified_remote' not found.
[140639050395904] Cannot quick reload all YAML configurations because the configuration is not valid: Integration error: unified_remote - Integration 'unified_remote' not found.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1849, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1889, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 874, in admin_handler
    await result
  File "/usr/src/homeassistant/homeassistant/components/homeassistant/__init__.py", line 316, in async_handle_reload_all
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Cannot quick reload all YAML configurations because the configuration is not valid: Integration error: unified_remote - Integration 'unified_remote' not found.
```

**Comment by DaviPtrs** [comment]
Comment/remove those lines you added to `configuration.yaml`, restart your HA (don't just reload the configuration, do a full restart), then you can add those lines and reload config

**Comment by stevland** [comment]
That worked!

Thank you for the quick response, and for developing and sharing this awesome integration.
